In [7]:
import torch

# Example logits tensor for a batch of data points
logits = torch.tensor([[1.0, 2.0, 3.0],
                       [1.0, 3.0, 2.0]])

# Applying softmax on the last dimension (num_classes)
softmax_probs = torch.softmax(logits, dim=-1)

print(softmax_probs)

print(logits.shape)
print(logits.shape[-1])

tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.6652, 0.2447]])
torch.Size([2, 3])
3


In [15]:
import numpy as np

def softmax(x):
    """Compute the softmax of vector x."""
    exp_x = np.exp(x - np.max(x))  # Subtracting np.max(x) for numerical stability
    
    print(exp_x)
    print("------")
    print(np.exp(-2)) # e ^ -2
    print(np.exp(-1)) # e ^ -1
    print(np.exp(0))  # e ^  0
    print("------")
    print(exp_x.shape)
    print(exp_x.sum(axis=0)) # Sum columns
    print(exp_x.sum(axis=-1)) # Sum rows
    print("------")
    
    return exp_x / exp_x.sum(axis=-1, keepdims=True)

# Example usage
x = np.array([[1.0, 2.0, 3.0],
              [1.0, 3.0, 2.0]])
softmax_values = softmax(x)

print(softmax_values)

[[0.13533528 0.36787944 1.        ]
 [0.13533528 1.         0.36787944]]
------
0.13533528323661267
0.3678794411714424
1.0
------
(2, 3)
[0.27067057 1.36787944 1.36787944]
[1.50321472 1.50321472]
------
[[0.09003057 0.24472847 0.66524096]
 [0.09003057 0.66524096 0.24472847]]
